name: create a comment on new work items or issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    # get github context of new issue/workitem 
    steps:
    - name: "dump github context"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
